### ISSUE TITLE
Socket logged error: no close frame received or sent

### ISSUE THREAD

**Issue by jayhuynh** [facebookresearch/Mephisto#1034]
## Issue Description

After I deployed my task, I leave it there without interating with it for a while (~4hours). Then it throw `Socket logged error: no close frame received or sent` and shut down my task.

Not sure if we have some connection timeout or sth like that.

According to https://websockets.readthedocs.io/en/stable/faq/common.html#what-does-connectionclosederror-no-close-frame-received-or-sent-mean. I guess this is abnormal

## Expected Behavior

It should maintain my websocket connection.

## Current Behavior

Throw `Socket logged error: no close frame received or sent` and shut down my task.

## Steps to Reproduce

1. Hydra config
```yml
#@package _global_
defaults:
  - /mephisto/blueprint: static_react_task
  - /mephisto/architect: heroku
  - /mephisto/provider: mock
mephisto:
  log_level: debug
  blueprint:
    data_json: ${task_dir}/image_urls.json
    task_source: ${task_dir}/webapp/build/bundle.js
    link_task_source: false
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 1
  task:
    task_name: pigmented-iris-t
    task_title: "Identify the presence and location of any pigmented iris freckles in the iris image."
    task_description: "Welcome to this crowdsourcing project, where your help is needed to identify pigmented iris freckles in iris images."
    task_reward: 0.5
    task_tags: "keypoints, keypoint, point, points"
    # We expect to be able to handle 3000 concurrent tasks without issue
    max_num_concurrent_units: 3000

```

2. python3 deploy.py

## Screenshots

```
[07/24/23 17:18:39] INFO     Prometheus server launched at        metrics.py:185
                             process 10
Running pre deployment hook

up to date, audited 785 packages in 5s

149 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> mephisto-task-compiler@1.0.1 dev
> webpack --mode production

asset build/bundle.js 233 KiB [emitted] [minimized] (name: main) 1 related asset
orphan modules 16.8 KiB [orphan] 3 modules
runtime modules 123 bytes 1 module
modules by path ./ 160 KiB
  modules by path ./node_modules/react/ 7.98 KiB 4 modules
  modules by path ./node_modules/react-dom/ 131 KiB
    ./node_modules/react-dom/client.js 619 bytes [built] [code generated]
    + 2 modules
  modules by path ./node_modules/scheduler/ 4.33 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.14 KiB [built] [code generated]
  ./src/main.js + 3 modules 17 KiB [built] [code generated]
modules by path ../../packages/ 156 KiB
  ../../packages/mephisto-task/build/bundle.js 134 KiB [built] [code generated]
  ../../packages/annotated/annotator-tracker/build/bundle.js 22.1 KiB [built] [code generated]
webpack 5.88.2 compiled successfully in 19135 ms
Locating heroku...
Getting heroku
/usr/local/bin/heroku
[07/24/23 17:19:16] INFO     Creating a task run under task      operator.py:262
                             name: pigmented-iris-t
[07/24/23 17:19:16] DEBUG    type of assignment data: <class task_launcher.py:86
                             'list'>
Building server files...

added 83 packages, and audited 84 packages in 5s

7 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Locating heroku...
/usr/local/bin/heroku
Heroku: Starting server...
[07/24/23 17:20:08] INFO     Sending alive              client_io_handler.py:243
                    INFO     Sending alive              client_io_handler.py:243
                    INFO     Sending alive              client_io_handler.py:243
                    INFO     Sending alive              client_io_handler.py:243
[07/24/23 17:20:09] INFO     Sending alive              client_io_handler.py:243
[07/24/23 17:20:09] INFO     channel open                websocket_channel.py:93
[07/24/23 17:20:09] DEBUG    Registered new unit MockUnit(29,        unit.py:297
                             created) for Assignment(29).

...
<more log here>
...
[07/24/23 21:21:57] INFO     Operator running task ID = 17       operator.py:528
[07/24/23 21:22:05] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:15] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:25] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:27] INFO     Operator running task ID = 17       operator.py:528
[07/24/23 21:22:35] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:45] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:55] DEBUG    Prometheus server appears to be      metrics.py:164
                             running at 9090
[07/24/23 21:22:57] INFO     Operator running task ID = 17       operator.py:528
[07/24/23 21:22:59] INFO     Socket logged error: no    websocket_channel.py:105
                             close frame received or
                             sent
```

## Environment

- Operating System: Docker container - Alpine:3.15
- Python: 3.8
- Prometheus - Grafana: enabled
- Project Version/Commit: [https://github.com/d-lab/pigmented-iris/tree/deployment-test/app](url)

## Additional Information

- This is the largest deployment we ever had around 3000 tasks concurrently
- Have never met this issue before with `Mturk` provider. It just shows up when we use `Mock` provider

## Possible Solution (Optional)

- Maybe we timout the connect somewhere, and would like to ask for more information to adjust it
