### ISSUE TITLE
Consider adding force_rebuild/post_install_script to your hydra config

### ISSUE THREAD

**Issue by Etesam913** [facebookresearch/Mephisto#811]
This warning error occurs when the force_rebuild and/or post_install_script parameters are not passed into the `build_custom_bundle()` method that you find in `run_task.py`.

To fix this first make sure that the force_rebuild and post_install_script parameters exist in the task field of your hydra_config file.

For example,

**Change this in your hydra config file**
```yaml
task:
  task_name: react-static-task-example
  task_title: "Rating a sentence as good or bad"
  task_description: "In this task, you'll be given a sentence. It is your job to rate it as either good or bad."
  task_reward: 0.05
  task_tags: "test,simple,button"
  # We expect to be able to handle 300 concurrent tasks without issue
  max_num_concurrent_units: 300
```

**to this:** 
```yaml
task:
  task_name: react-static-task-example
  task_title: "Rating a sentence as good or bad"
  task_description: "In this task, you'll be given a sentence. It is your job to rate it as either good or bad."
  task_reward: 0.05
  task_tags: "test,simple,button"
  # We expect to be able to handle 300 concurrent tasks without issue
  max_num_concurrent_units: 300
  post_install_script: ""
  force_rebuild: false
```

**Then in run_task.py change this**
```python
build_custom_bundle(task_dir)
```

**to:**
```python
build_custom_bundle(
    task_dir,
    force_rebuild=cfg.mephisto.task.force_rebuild
    post_install_script=cfg.mephisto.task.post_install_script,
)
```
