### ISSUE TITLE
Buggy behaviour on MTurk

### ISSUE THREAD

**Issue by mjkanji** [facebookresearch/Mephisto#967]
While trying to run Mephisto in the MTurk Sandbox, I noticed some rather unusual behaviour. In terms of configuration, the only changes I made are to enable both screening and onboarding at the same time, and having 4 tasks instead of the default 2 in `static_react_task`.

<details>
<summary>Config and data changes</summary>

Changes to `run_task.py`:

```python
static_task_data=[
     {"text": "This text is good text!"},
     {"text": "This text is bad text!"},
     {"text": "This is neutral text!"},
     {"text": "This is text text!"}
 ]
```
Config file:

```yaml
#@package _global_
defaults:
  - /mephisto/blueprint: static_react_task
  - /mephisto/architect: heroku
  - /mephisto/provider: mturk_sandbox
mephisto:
  provider:
    requester_name: my_mturk_sandbox
  blueprint:
    task_source: ${task_dir}/webapp/build/bundle.js
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 1
    onboarding_qualification: test-react-static-onboarding-qualification-003
    passed_qualification_name: "test-react-static-passed_qualification-003"
    block_qualification: "test-react-static-blocked-qualification-003"
    use_screening_task: true
    max_screening_units: 1
  task:
    task_name: react-static-task-example-003
    task_title: "Rating a sentence as good or bad"
    task_description: "In this task, you'll be given a sentence. It is your job to rate it as either good or bad."
    task_reward: 0.05
    task_tags: "test,simple,button"
    # We expect to be able to handle 300 concurrent tasks without issue
    max_num_concurrent_units: 300
    allowed_concurrent: 1
```
</details>

Please see the video below.

https://app.usebubbles.com/dpCa29UFnyhXGkGRFGkqHq/mephisto-sandbox-bug

For one, note that the user gets the "there is no available work" error as soon as the screening task is complete, even though all of the "main" tasks are remaining. This may make workers assume that there are no more tasks and make them move on to another HIT.

Secondly, note that the worker is only able to complete 2 of the "main" tasks (3 if you include the screening unit), out of a total of 4 tasks before MTurk returns an error that "There are no more of these HITs available". The config does not impose a `maximum_units_per_worker` limit and so the worker should have been able to complete all 4 tasks (5 including the screening task). 

The other thing to note is that if a screening task is included, Mephisto does not seem to increment the total number of tasks in MTurk UI automatically. That is, the maximum number of tasks we see is 4, while there should be 5 (to accommodate the screening task at the start).

All of this results in the task server running forever (because it still has 2 tasks incomplete), while the workers are blocked from these tasks, ultimately requiring a `Ctrl + C` to kill the server.
